name: OurFamilyLedger
options:
  bundleIdPrefix: com.ourfamilyledger
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  OurFamilyLedger:
    type: application
    platform: iOS
    sources:
      - path: OurFamilyLedger
        excludes:
          - "**/*.xcassets"
    resources:
      - path: OurFamilyLedger/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xiaoquisme.ourfamilyledger
        INFOPLIST_FILE: OurFamilyLedger/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "需要访问相册以选择截图进行记账识别"
        INFOPLIST_KEY_NSCameraUsageDescription: "需要使用相机拍摄小票进行记账识别"
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []

schemes:
  OurFamilyLedger:
    build:
      targets:
        OurFamilyLedger: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
